backend:
  name: github
  branch: main
  repo: "jc-tamu/it-ae-doc-testing"
  base_url: http://decap-test.tamu-lab.workers.dev
  auth_endpoint: /auth

site_url: https://jc-tamu.github.io/it-ae-doc-testing/

publish_mode: editorial_workflow
media_folder: static/img

collections: # A list of collections the CMS should be able to edit
  - name: "docs"
    label: "Docs"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    description: "Documentation pages"
    editor:
      visualEditing: true
    sortable_fields:
      - title
      - { field: date, default_sort: desc }
      - draft
    fields: # The fields each document in this collection have
      - { label: "Title", name: "title", widget: "string", tagname: "h1" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - {
          label: "Body",
          name: "body",
          widget: "richtext",
          hint: "Main content goes here.",
        }
